print('Calculadora do Indice de Massa Corporal (IMC)')
nome=input('Qual o seu nome?')
print('Olá,'+nome+'. Seja bem vindo(a)!')
peso=input('Qual o seu peso corporal?')
peso=float (peso)
altura=input('Qual sua altura em metros?')
altura=float (altura)
dados= ('Digite a tecla Enter para saber seu IMC')
print('Seu IMC, é:' + str(peso / (altura**2)))