print('=====CALCULO DA MÉDIA ANUAL=====')
n1 = (float(input('Nota do primeiro bimestre:')))
n2 = (float(input('Nota do segundo bimestre:')))
n3 = (float(input('Nota do terceiro bimestre:')))
n4 = (float(input('Nota do quarto bimestre:')))
m = ((n1+n2+n3+n4) / 4)
resto=(6.0-m)
print('Sua média anual, é: {:3}'.format(m))
print('Você precisa de {:3} para ser APROVADO por média!'.format(resto))
